// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P9_Backend.DAL;

namespace P9_Backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201001114520_PosUUIDToIDAutoInc")]
    partial class PosUUIDToIDAutoInc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("P9_Backend.Models.Drone", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("BatteryPercentage")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentPositionID")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UUID");

                    b.HasIndex("CurrentPositionID");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("P9_Backend.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Altitude")
                        .HasColumnType("double");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("P9_Backend.Models.Drone", b =>
                {
                    b.HasOne("P9_Backend.Models.Position", "CurrentPosition")
                        .WithMany()
                        .HasForeignKey("CurrentPositionID");
                });
#pragma warning restore 612, 618
        }
    }
}
